//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityPortalLogical.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CotizacionDetalle
    {
        public int CodCotizacion { get; set; }
        public int NumLinea { get; set; }
        public int CodProducto { get; set; }
        public int CantidadProducto { get; set; }
        public int PrecioProducto { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
