//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityPortalLogical.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacion
    {
        public int Codigo { get; set; }
        public System.DateTime Fecha { get; set; }
        public int CodCliente { get; set; }
        public string Moneda { get; set; }
        public int PorcentajeDescuento { get; set; }
        public double SubTotal { get; set; }
        public double Descuento { get; set; }
        public double Iva { get; set; }
        public double Total { get; set; }
        public string UsuarioCrea { get; set; }
        public System.DateTime FechaCrea { get; set; }
        public string UsuarioModifica { get; set; }
        public System.DateTime FechaModifica { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
