//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityPortalLogical.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distrito
    {
        public Distrito()
        {
            this.Cliente = new HashSet<Cliente>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int Codigo { get; set; }
        public int Cod_Canton { get; set; }
        public string Nombre { get; set; }
        public string Estado { get; set; }
        public string UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public string UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual Canton Canton { get; set; }
        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
