//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityPortalLogical.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfil
    {
        public Perfil()
        {
            this.Permiso = new HashSet<Permiso>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int Codigo { get; set; }
        public string Nombre { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<Permiso> Permiso { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
