//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityPortalLogical.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public Permiso()
        {
            this.Permiso1 = new HashSet<Permiso>();
            this.Perfil = new HashSet<Perfil>();
        }
    
        public int Codigo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
        public int CodPadre { get; set; }
        public bool EsFormulario { get; set; }
        public string PathFormulario { get; set; }
        public string Icono { get; set; }
    
        public virtual ICollection<Permiso> Permiso1 { get; set; }
        public virtual Permiso Permiso2 { get; set; }
        public virtual ICollection<Perfil> Perfil { get; set; }
    }
}
