//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityPortalLogical.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.ContratoDetalle = new HashSet<ContratoDetalle>();
            this.CotizacionDetalle = new HashSet<CotizacionDetalle>();
        }
    
        public int Codigo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int CantidadExistencia { get; set; }
        public double Precio { get; set; }
        public double PrecioDolar { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<ContratoDetalle> ContratoDetalle { get; set; }
        public virtual ICollection<CotizacionDetalle> CotizacionDetalle { get; set; }
    }
}
